[npm-publish] Adds npm config
elo7/event-amd pull request #2
Opened 2016-12-19 16:05 UTC by tcelestino

@tisvasconcelos @rapahaeru

2017-01-02 12:10 UTC, FernandaBernardo requested changes

2017-01-02 12:10 UTC, FernandaBernardo commented on bower.json
> +  "version": "1.0.5",
Não seria bom subir a versão *minor* (como no format-amd e no async-define) em vez da versão *patch*?

@luiz

2017-01-02 12:10 UTC, FernandaBernardo commented
Que tal adicionar um `.travis.yml` para corrigir os testes no Travis?

@luiz

2017-01-02 12:21 UTC, FernandaBernardo commented
Está dando warning no `npm install`:

```
npm WARN elo7-events-amd@1.0.5 license should be a valid SPDX license expression
```

@luiz

2017-01-03 11:40 UTC, luiz commented
Continua dando o warning da licença:

```
npm WARN elo7-events-amd@1.1.0 license should be a valid SPDX license expression
```

@luiz

2017-01-03 11:43 UTC, luiz commented
Não diretamente relacionado com a história, mas que tal corrigir o nome do projeto no LICENSE?

@luiz

2017-01-16 11:57 UTC, luiz commented on package.json
> +    "define-async": "1.1.0"
Não seria melhor usar a versão 1.1.1?

2017-01-30 16:05 UTC, luiz commented on bower.json
> +  "version": "1.1.3",
Não encontrei nem essa versão nem a versão `1.1.2` no npm. Está certo? E não deveria ser uma versão `SNAPSHOT`?

@luiz

2017-01-30 16:05 UTC, luiz commented on package.json
> +  "version": "1.1.3",
Não encontrei nem essa versão nem a versão `1.1.2` no npm. Está certo? E não deveria ser uma versão `SNAPSHOT`?

@luiz

2017-01-30 16:19 UTC, luiz commented
Lembrar de atualizar o `package.json` após o rebase, se necessário.

@luiz

2017-02-08 15:56 UTC, merged